### ISSUE TITLE
For Python version 3.10.12 is 2997

### ISSUE THREAD

**Issue by mdtrooper** [rafalagoon/not_enough_nots#3]
Hi.

I am trying the python and the current code is not run.

```
$ python3 not.py 
RecursionError: maximum recursion depth exceeded during compilation
```

```
$ python3 --version
Python 3.10.12
```

The number of not for my version is:

```
$ tail -n +4 not.py | head -n -4 | tr ' ' '\n' | grep -c not
```

**Comment by rafalagoon** [comment]
I think that depends on many many many many many things: version, subversion, subsubversion, memory, the moon... I don't know xD

I just tested it one more time and you are right. I have the same version and it breaks... I think that at the last moment I changed something to test it and I broke it. I'm going to update it!

**Comment by rafalagoon** [comment]
Corrected!
